spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/musicdb?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:  # Connection pool retry
      connection-timeout: 60000
      maximum-pool-size: 10
      initialization-fail-timeout: 0  # NÃ£o falha startup
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    connect-retries: 10
    connect-retries-interval: 500

management:
  endpoints:
    web:
      exposure:
        include: health,info
